<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_events"
 *
 * Auto generated by Extension Builder 2015-07-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RKW Events',
	'description' => 'Provides a possibility to list and handle events',
	'category' => 'plugin',
    'author' => 'Carlos Meyer, Maximilian Fäßler, Steffen Kroggel',
    'author_email' => 'cm@davitec.de, maximilian@faesslerweb.de, developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.7',
	'constraints' => array(
        'depends' => array(
            'extbase' => '6.2.0-7.6.99',
            'fluid' => '6.2.0-7.6.99',
            'typo3' => '6.2.0-7.6.99',
            'static_info_tables' => '6.5',
            'rkw_basics' => '7.6.10-7.6.99',
            'rkw_mailer' => '7.6.10-7.6.99',
            'rkw_survey' => '7.6.2-1.9.99'
        ),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);