routeEnhancers:
  RkwEvents:
    type: Extbase
    namespace: 'tx_rkwevents_pi1'
    routes:
      - routePath: '/rkw-events/show/{event}'
        _controller: 'Event::show'
        _arguments:
          event1: event
      - routePath: '/rkw-events/list'
        _controller: 'Event::list'
      - routePath: '/rkw-events/list/{page}'
        _controller: 'Event::list'
      - routePath: '/rkw-eventreservation/{event}'
        _controller: 'EventReservation::new'
      - routePath: '/rkw-eventreservation/create'
        _controller: 'EventReservation::create'
      - routePath: '/rkw-eventreservation/edit/{eventReservation}'
        _controller: 'EventReservation::edit'
      - routePath: '/rkw-eventreservation/update'
        _controller: 'EventReservation::update'
      - routePath: '/rkw-eventreservation/myevents/{event}'
        _controller: 'EventReservation::myEvents'
      - routePath: '/rkw-eventreservation/optin/{event}/{tokenUser}/{token}'
        _controller: 'EventReservation::optIn'
    defaultController: 'Event::list'
    requirements:
      page: '[0-9]{1,10}'
      eventReservation: '[0-9]{1,10}'
      tokenUser: '[a-zA-Z0-9]{30}'
      token: '[a-zA-Z0-9]{30}'
    aspects:
      event:
        type: EventPersistentSlugifiedPatternMapper
        tableName: 'tx_rkwevents_domain_model_event'
        routeFieldPattern: '^(.*)-(?P<uid>\d+)$'
        routeFieldResult: '{title|sanitized}-{uid}'
  RkwEvents1:
    type: Extbase
    namespace: 'tx_rkwevents_prefiltered'
    routes:
      - routePath: '/rkw-events/filtered-list'
        _controller: 'Event::listPrefiltered'
      - routePath: '/rkw-events/filtered-list/{page}'
        _controller: 'Event::listPrefiltered'
    defaultController: 'Event::listPrefiltered'
    requirements:
      page: '[0-9]{1,10}'
  RkwEvents2:
    type: Extbase
    namespace: 'tx_rkwevents_similar'
    routes:
      - routePath: '/rkw-events/similar-list'
        _controller: 'Event::listSimilar'
      - routePath: '/rkw-events/similar-list/{page}'
        _controller: 'Event::listSimilar'
    defaultController: 'Event::listSimilar'
    requirements:
      page: '[0-9]{1,10}'
